name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: read-all

jobs:
  build-linux:
    permissions:
      contents: read
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4
      with:
        egress-policy: audit
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
        submodules: 'recursive'
    - name: Generate
      run: mkdir build && cd build && cmake -G 'Unix Makefiles' ..
    - name: Build
      run: cd build && cmake --build .
    - name: Upload
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: bin-linux
        path: |
          build/**/*.so
          build/**/netcommapp
          build/**/dsapp
  build-macos-x64:
    permissions:
      contents: read
    name: Build macOS (x64)
    runs-on: macos-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4
      with:
        egress-policy: audit
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
        submodules: 'recursive'
    - name: Generate
      run: mkdir build && cd build && cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15" ..
    - name: Build
      run: cd build && cmake --build .
    - name: Upload
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: bin-macos-x64
        path: |
          build/**/*.dylib
          build/**/netcommapp
          build/**/dsapp
  build-macos-x64:
    permissions:
      contents: read
    name: Build macOS (arm64)
    runs-on: macos-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4
      with:
        egress-policy: audit
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
        submodules: 'recursive'
    - name: Generate
      run: mkdir build && cd build && cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0" ..
    - name: Build
      run: cd build && cmake --build .
    - name: Upload
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: bin-macos-arm64
        path: |
          build/**/*.dylib
          build/**/netcommapp
          build/**/dsapp
  build-windows:
    permissions:
      contents: read
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
        submodules: 'recursive'
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1.14.2
      with:
        perl-version: '5.34'
    - name: Install NASM
      uses: ilammy/setup-nasm@v1.2.1
    - name: Generate
      run: mkdir build && cd build && cmake -G 'Visual Studio 17 2022' -A x64 ..
    - name: Build
      run: cd build && cmake --build .
    - name: Upload
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: bin-windows
        path: |
          build/**/*.dll
          build/**/netcommapp.exe
          build/**/dsapp.exe
